// Generated by web/scripts/generate-stories.mjs. Do not hand-edit story entries here.
export type StorySeed = {
  headline: string
  badge: 'new' | 'updated'
  summary: string
  whyItMatters: string
  sourceName: string
  sourceUrl: string
  termNames: string[]
  publishedAt: string
}

export const generatedAt = '2026-08-02T09:15:46.797Z'

export const storySeeds: StorySeed[] = [
  {
    "headline": "The Greenhouse and the Lens: Two Modes of Agentic AI Work",
    "badge": "new",
    "summary": "My Photography Threads Instagram GitHub LinkedIn Email Me Menu Home Blog Categories Archive RSS Feed Links A greenhouse and a lens both run on sunlight, and they do opposite things with it. The greenhouse traps ambient heat and holds it, so everything inside grows a little faster than it would outside: flowers, herbs, weeds, whatever happens to be in the soil.",
    "whyItMatters": "This matters because it changes the shape of work, not just software.  People may spend less time doing routine tasks and more time checking, directing, and fixing AI output.",
    "sourceName": "brethorsting.com",
    "sourceUrl": "https://www.brethorsting.com/blog/2026/08/the-greenhouse-and-the-lens-two-modes-of-agentic-ai-work",
    "termNames": [
      "Artificial Intelligence (AI)",
      "AI Agent"
    ],
    "publishedAt": "2026-08-02T00:06:25.000Z"
  },
  {
    "headline": "AI opens new era in cognitive studies of wild primates",
    "badge": "new",
    "summary": "Emory anthropologists created an AI system to automate behavioral studies of capuchins monkeys in the wild. The novel method provides a roadmap for the first scalable, systematic way to evaluate and monitor the cognitive abilities of wild primates.",
    "whyItMatters": "The useful question is not whether this sounds futuristic.  It is whether it changes a real decision for workers, customers, developers, schools, governments, or families.",
    "sourceName": "news.emory.edu",
    "sourceUrl": "https://news.emory.edu/features/2026/07/ai-opens-new-era-cognitive-studies-wild-primates",
    "termNames": [
      "Artificial Intelligence (AI)"
    ],
    "publishedAt": "2026-08-01T22:40:22.000Z"
  },
  {
    "headline": "AI's real threat to jobs isn't job loss, it's lower paychecks, new research says",
    "badge": "new",
    "summary": "Roles with a high exposure to AI have seen sharp declines in real wages in recent years, according to a new whitepaper from Apollo.",
    "whyItMatters": "This matters because it changes the shape of work, not just software.  People may spend less time doing routine tasks and more time checking, directing, and fixing AI output.",
    "sourceName": "businessinsider.com",
    "sourceUrl": "https://www.businessinsider.com/ai-could-lower-workers-pay-job-market-impact-2026-7",
    "termNames": [
      "Artificial Intelligence (AI)"
    ],
    "publishedAt": "2026-08-01T21:05:00.000Z"
  },
  {
    "headline": "Judge denies xAI’s request to block Minnesota ban on ‘nudify’ apps",
    "badge": "new",
    "summary": "Despite a lawsuit from xAI, a Minnesota ban on apps that allow users to “nudify” images can move forward.",
    "whyItMatters": "AI infrastructure now carries real-world costs like power, pollution, and local pushback.  Once defense and AI get tied together, the policy stakes get much bigger.",
    "sourceName": "TechCrunch AI",
    "sourceUrl": "https://techcrunch.com/2026/08/01/judge-denies-xais-request-to-block-minnesota-ban-on-nudify-apps",
    "termNames": [
      "Artificial Intelligence (AI)",
      "xAI",
      "Tool"
    ],
    "publishedAt": "2026-08-01T20:26:04.000Z"
  },
  {
    "headline": "YouTuber Hank Green says his AI usage is ‘not healthy’",
    "badge": "new",
    "summary": "The controversy started when, in the middle of a video posted on the educational channel Complexly , Green incongruously used the phrase “I appreciate the pushback,” leading viewers to speculate that he’d written the script with a chatbot — and, in the process, accidentally included its response to one of his prompts. In a since-deleted post on X, Green acknowledged that he’d.",
    "whyItMatters": "AI video is expensive enough that even large consumer apps are reorganizing around the cost.  That matters for users because the flashiest AI features may become separate products, paid tools, or experiments that disappear if the math does not work.",
    "sourceName": "TechCrunch AI",
    "sourceUrl": "https://techcrunch.com/2026/08/01/youtuber-hank-green-says-his-ai-usage-is-not-healthy",
    "termNames": [
      "Artificial Intelligence (AI)"
    ],
    "publishedAt": "2026-08-01T19:45:45.000Z"
  },
  {
    "headline": "Is this Billboard Hot 100 hit AI slop?",
    "badge": "new",
    "summary": "Entertainment Close Entertainment Posts from this topic will be added to your daily email digest and your homepage feed. Report Close Report Posts from this topic will be added to your daily email digest and your homepage feed.",
    "whyItMatters": "The useful question is not whether this sounds futuristic.  It is whether it changes a real decision for workers, customers, developers, schools, governments, or families.",
    "sourceName": "The Verge AI",
    "sourceUrl": "https://www.theverge.com/ai-artificial-intelligence/974209/fenix-flexin-billboard-hot-100-rubberz-ai-slop",
    "termNames": [
      "Artificial Intelligence (AI)"
    ],
    "publishedAt": "2026-08-01T18:20:00.000Z"
  }
]
