// Generated by web/scripts/generate-stories.mjs. Do not hand-edit story entries here.
export type StorySeed = {
  headline: string
  badge: 'new' | 'updated'
  summary: string
  whyItMatters: string
  sourceName: string
  sourceUrl: string
  termNames: string[]
  publishedAt: string
}

export const generatedAt = '2026-09-03T09:15:39.176Z'

export const storySeeds: StorySeed[] = [
  {
    "headline": "Go grandmaster Shin defeats AI KataGo in historic human victory",
    "badge": "new",
    "summary": "Shin Jin-seo, the world's top-ranked Go player, on Tuesday completed a dramatic comeback against the world’s premier artificial intelligence Go engine, KataGo, claiming a historic human victory over AI. Shin, who holds the game's highest achievable rank of nine-dan, dealt KataGo a decisive 11.5-point defeat playing black in 221 moves in the series finale, which took three hours.",
    "whyItMatters": "This matters because it changes the shape of work, not just software.  People may spend less time doing routine tasks and more time checking, directing, and fixing AI output.",
    "sourceName": "kedglobal.com",
    "sourceUrl": "https://www.kedglobal.com/artificial-intelligence/newsView/ked202607210007",
    "termNames": [
      "Artificial Intelligence (AI)"
    ],
    "publishedAt": "2026-09-03T01:11:22.000Z"
  },
  {
    "headline": "US gov sides with OpenAI on issue of training LLMs on copyrighted material",
    "badge": "new",
    "summary": "\"The United States has a strong interest in continuing to develop a robust and competitive artificial intelligence industry that sets the standard for the practice and procedure of AI use globally,\" the brief reads.",
    "whyItMatters": "Model changes show up in the tools people already use for writing, coding, studying, and research.  Small changes upstream can change what feels easy or risky downstream.",
    "sourceName": "techcrunch.com",
    "sourceUrl": "https://techcrunch.com/2026/09/02/u-s-government-sides-with-openai-on-issue-of-training-llms-on-copyrighted-material",
    "termNames": [
      "Artificial Intelligence (AI)",
      "Chatbot",
      "Model"
    ],
    "publishedAt": "2026-09-03T00:54:01.000Z"
  },
  {
    "headline": "TechCrunch Disrupt 2026’s new Real World AI Stage features Nvidia, robots, and extinct animals",
    "badge": "new",
    "summary": "On our new Real World AI stage, we’ll be focusing on the intersection between the digital and physical, and all the ways we’ll continue to see a blending of the two.",
    "whyItMatters": "The useful question is not whether this sounds futuristic.  It is whether it changes a real decision for workers, customers, developers, schools, governments, or families.",
    "sourceName": "TechCrunch AI",
    "sourceUrl": "https://techcrunch.com/2026/09/02/techcrunch-disrupt-2026s-new-real-world-ai-stage-features-nvidia-robots-and-extinct-animals",
    "termNames": [
      "Artificial Intelligence (AI)",
      "GPU"
    ],
    "publishedAt": "2026-09-02T22:24:09.000Z"
  },
  {
    "headline": "OpenAI’s new reasoning technique alarms AI safety experts",
    "badge": "new",
    "summary": "OpenAI’s new Astra model will use “recurrent depth,” a technique that allows the model to operate outside of the sequential thinking that characterizes most reasoning models.",
    "whyItMatters": "For normal people, this is the boring part that matters most: whether AI systems can be trusted when money, data, laws, or public safety are involved.",
    "sourceName": "TechCrunch AI",
    "sourceUrl": "https://techcrunch.com/2026/09/02/openais-new-reasoning-technique-alarms-ai-safety-experts",
    "termNames": [
      "Artificial Intelligence (AI)",
      "Chatbot",
      "AI Safety"
    ],
    "publishedAt": "2026-09-02T20:19:14.000Z"
  },
  {
    "headline": "AI is stopping startups from completing puberty",
    "badge": "new",
    "summary": "Puberty is that in-between bit between seed stage and a startup working out what it actually needs to be in order to thrive. If you've been in a seed or Series A or B startup, or even an early stage product in a larger company, you will likely",
    "whyItMatters": "This matters because it changes the shape of work, not just software.  People may spend less time doing routine tasks and more time checking, directing, and fixing AI output.",
    "sourceName": "ashley.rolfmore.com",
    "sourceUrl": "https://ashley.rolfmore.com/ai-is-stopping-startups-from-completing-puberty",
    "termNames": [
      "Artificial Intelligence (AI)"
    ],
    "publishedAt": "2026-09-02T18:06:14.000Z"
  },
  {
    "headline": "Amazon’s AI assistant can now spot fake emails from the company",
    "badge": "new",
    "summary": "Amazon is trying to combat impersonation scams with a new feature that allows you to use its AI assistant to determine whether an email, text message, or phone call actually came from the company. With the update, you can ask Alexa for Shopping about a message you received, and it will use AI to compare […]",
    "whyItMatters": "The useful question is not whether this sounds futuristic.  It is whether it changes a real decision for workers, customers, developers, schools, governments, or families.",
    "sourceName": "The Verge AI",
    "sourceUrl": "https://www.theverge.com/tech/988518/amazon-alexa-for-shopping-verify-emails",
    "termNames": [
      "Artificial Intelligence (AI)"
    ],
    "publishedAt": "2026-09-02T17:52:56.000Z"
  }
]
